"""Added local time to jobs

Revision ID: 2a7867deda68
Revises: 7c6910ba079f
Create Date: 2026-03-01 22:00:53.484698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a7867deda68'
down_revision = '7c6910ba079f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied_utc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_applied_local', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_applied_local')
        batch_op.drop_column('date_applied_utc')

    # ### end Alembic commands ###
