"""Added timezone in users table

Revision ID: 7c6910ba079f
Revises: eaf0b7d09674
Create Date: 2026-03-01 21:15:26.716236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6910ba079f'
down_revision = 'eaf0b7d09674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('local_time')

    # ### end Alembic commands ###
