"""Removed url column from Resume table

Revision ID: 890123eda0fe
Revises: b7dd21bde0e1
Create Date: 2026-04-02 22:27:34.283948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890123eda0fe'
down_revision = 'b7dd21bde0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
