"""Changed jobs table to only have one date and time

Revision ID: 9e74b21ae9c0
Revises: 2a7867deda68
Create Date: 2026-03-01 22:43:26.424021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e74b21ae9c0'
down_revision = '2a7867deda68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', sa.Date(), nullable=True))
        batch_op.drop_column('date_applied_utc')
        batch_op.drop_column('date_applied_local')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied_local', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_applied_utc', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###
