"""Added column to resume for the new file name

Revision ID: b7dd21bde0e1
Revises: c48474f0e6d9
Create Date: 2026-04-02 21:54:33.224013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dd21bde0e1'
down_revision = 'c48474f0e6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_filename', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('new_filename')

    # ### end Alembic commands ###
