"""Updated sub to google_sub in users table

Revision ID: e5c4cd07e3b2
Revises: afc5c40ae173
Create Date: 2026-02-28 19:50:38.506815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c4cd07e3b2'
down_revision = 'afc5c40ae173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_sub_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['google_sub'])
        batch_op.drop_column('sub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_sub_key'), ['sub'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('google_sub')

    # ### end Alembic commands ###
