"""modified user table, added support for magic link login

Revision ID: fd28977347ee
Revises: 6b0d61562ed0
Create Date: 2026-06-04 17:39:11.940635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd28977347ee'
down_revision = '6b0d61562ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stytch_user_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('google_sub',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint(None, ['stytch_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('google_sub',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('stytch_user_id')

    # ### end Alembic commands ###
